name: release

on:
  push:
    tags: ["v*"]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.1"
          gleam-version: "0.33.0"

      - run: |
          version="v$(cat gleam.toml | grep -m 1 "version" | sed -r "s/version *= *\"([[:digit:].]+)\"/\1/")"
          if [ "$version" != "${{ github.ref_name }}" ]; then
            echo "tag '${{ github.ref_name }}' does not match the version in gleam.toml"
            echo "expected a tag name 'v$version'"
            exit 1
          fi
        name: check version

      - run: gleam format --check

      - run: gleam test

      - run: gleam publish -y
        env:
          HEXPM_USER: ${{ secrets.HEX_USERNAME }}
          HEXPM_PASS: ${{ secrets.HEX_PASSWORD }}

      - uses: softprops/action-gh-release@v1
